### ISSUE TITLE
Installing on Ubuntu 13.10 fails

### ISSUE THREAD

**Issue by skarjoko** [headius/ruby-atomic#38]
Trying to install on my Ubuntu 13.10 server, however it fails with this message.

```
$ sudo gem install atomic -v 1.1.14
Fetching: atomic-1.1.14.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing atomic:
        ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from extconf.rb:13:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/atomic-1.1.14 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/atomic-1.1.14/ext/gem_make.out
```

I'm following the instructions for installing GitLab, which specified installing with the version number as a parameter.

**Comment by juhoffma** [comment]
Hmm, yours seems to be that the ubuntu server cannot locate the command mkmf. I guess all you have to do is install the package `apt-get install ruby1.9.1-dev`

**Comment by juhoffma** [comment]
mine is more realated to 

```
17:54 $ gem install atomic -v 1.1.14
ERROR:  Could not find a valid gem 'atomic' (= 1.1.14), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://s3.amazonaws.com/production.s3.rubygems.org/specs.4.8.gz)
```

**Comment by skarjoko** [comment]
Sorry for the late reply, but installing ruby1.9.1-dev fixed it for me. Thanks!
